application: cloud-training-
api_version: alpha005
runtime: python27
version: 1
threadsafe: true

handlers:
- url: /user/.*
  script: main.app
  login: required
  secure: always

- url: /.*/add_opportunity
  script: main.app
  login: required
  secure: always

- url: /.*
  script: main.app
  login: required
  secure: always

libraries:
- name: jinja2
  version: latest